name: "Build and Test"

on:
  push:
    branches: [ release ]
  pull_request:
    branches: ["*"]
  workflow_dispatch: ~

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
    # There are too many lint errors in current code bases
    # uncomment when we decide what lint should be addressed or ignored.
    # - run: make lint
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: "Checkout ${{ github.ref }}"
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup Golang Caches
        uses: actions/cache@v3
        with:
          path: |-
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-go

      - run: git stash # restore patch

      - name: "Build Higress Operator Binary"
        run: GOPROXY="https://proxy.golang.org,direct" make build

      - name: Upload Higress Binary
        uses: actions/upload-artifact@v4
        with:
          name: higress
          path: out/

  higress-conformance-test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3

      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup Golang Caches
        uses: actions/cache@v3
        with:
          path: |-
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-go

      - name: Setup Submodule Caches
        uses: actions/cache@v3
        with:
          path: |-
            envoy
            istio
            external
            .git/modules
          key: ${{ runner.os }}-submodules-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-submodules

      - run: git stash # restore patch

      - name: "Run Higress Operator E2E Tests"
        run: GOPROXY="https://proxy.golang.org,direct" make higress-operator-test
