name: "Build and Test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: ["*"]
  workflow_dispatch: ~

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
    # There are too many lint errors in current code bases
    # uncomment when we decide what lint should be addressed or ignored.
    # - run: make lint
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: "Checkout ${{ github.ref }}"
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup Golang Caches
        uses: actions/cache@v3
        with:
          path: |-
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-go

      - run: git stash # restore patch

      - name: "Build Higress Operator Binary"
        run: GOPROXY="https://proxy.golang.org,direct" make docker-build

      - name: Upload Higress Binary
        uses: actions/upload-artifact@v4
        with:
          name: higress
          path: out/